resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/net-config-static-bridge.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/net-config-static.yaml
parameter_defaults:
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 10.98.0.1
  NeutronPublicInterface: nic2
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DockerInsecureRegistryAddress:
    - registry-proxy.engineering.redhat.com
