---
name: build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  push_to_reg:
    if: github.repository_owner == 'os-migrate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo 'hello world'

